/* IGMCRI Surgery UI enhancements: mobile-first OPD, autocomplete, autopopulation and waiting-list filters. */
(function(){
  const client=supabase.createClient(IGMCRI_CONFIG.supabaseUrl,IGMCRI_CONFIG.supabasePublishableKey);
  const DOCTORS=['Dr Simon D. Dasiah','Dr Basavanandaswamy','Dr Rayganapathy','Dr Srivengadesh G','Dr Kapil Baliga','Dr Selvakumaran','Dr Ashley Solomon','Dr Mima Maychet Sangma','Dr Ganesan','Dr Govardhanan','Dr Ray'];
  const UNITS=['S1','S2','S3','S4','S5','S6'];
  const MAJOR_PROCS=['Laparoscopic cholecystectomy','Laparoscopic appendicectomy','Open appendicectomy','Laparoscopic hernia repair','Open hernia repair','Thyroidectomy','Hemithyroidectomy','Modified radical mastectomy','Breast lumpectomy','Colectomy','Bowel resection and anastomosis','Exploratory laparotomy','Incisional hernia repair','Ventral hernia repair','Haemorrhoidectomy','Fistulectomy','Fissurectomy'];
  const MINOR_PROCS=['Excision biopsy','Incision and drainage','Wound debridement','Suturing','Abscess drainage','Lipoma excision','Sebaceous cyst excision','Nail procedure','Skin lesion excision','Suture removal'];
  const ENDO_PROCS=['Upper GI endoscopy','Colonoscopy','Flexible sigmoidoscopy','Diagnostic endoscopy','Endoscopic biopsy'];
  const DIAGNOSES=['Cholelithiasis','Acute appendicitis','Inguinal hernia','Incisional hernia','Ventral hernia','Umbilical hernia','Pilonidal sinus','Haemorrhoids','Anal fissure','Fistula-in-ano','Breast lump','Thyroid swelling','Lipoma','Sebaceous cyst','Non-healing ulcer','Wound infection'];
  const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function datalist(id,items){if($(id))return;const d=document.createElement('datalist');d.id=id;d.innerHTML=items.map(x=>`<option value="${esc(x)}"></option>`).join('');document.body.appendChild(d)}
  function addListInput(id,items){const el=$(id);if(!el||el.tagName==='SELECT')return;const lid=id+'-suggestions';datalist(lid,items);el.setAttribute('list',lid);el.setAttribute('autocomplete','off')}
  function setValue(id,val){const e=$(id);if(e&&val!==undefined&&val!==null)e.value=val||''}
  function populatePatient(p,prefix='p'){if(!p)return;setValue(prefix+'name',p.name);setValue(prefix+'hno',p.hospital_no);setValue(prefix+'opno',p.op_no);setValue(prefix+'ipno',p.ip_no);setValue(prefix+'age',p.age);setValue(prefix+'sex',p.sex);setValue(prefix+'mobile',p.mobile);setValue(prefix+'bg',p.blood_group);setValue(prefix+'address',p.address);document.querySelectorAll('.patient-autofill-note').forEach(x=>x.remove());const first=$(prefix+'name');if(first){const n=document.createElement('div');n.className='patient-autofill-note success-note';n.textContent='✓ Existing patient selected — details auto-populated';first.parentElement.appendChild(n)}}
  window.usePatient=function(p){window.selectedPatient=p;if($('pname'))populatePatient(p,'p');if($('qname'))populatePatient(p,'q');if(window.toast)window.toast('Patient selected: '+p.name)};
  function enhancePatientFields(prefix){const mobile=$(prefix+'mobile');if(mobile){mobile.type='tel';mobile.inputMode='numeric';mobile.placeholder='10-digit mobile number';mobile.maxLength=10;mobile.pattern='[6-9][0-9]{9}';if(!mobile.dataset.enhanced){mobile.dataset.enhanced='1';mobile.addEventListener('input',()=>{mobile.value=mobile.value.replace(/\D/g,'').slice(0,10)})}}const name=$(prefix+'name');if(name)name.autocomplete='name';const address=$(prefix+'address');if(address)address.autocomplete='street-address';const photo=$(prefix+'photo');if(photo)photo.setAttribute('capture','environment')}
  function enhanceOPD(){enhancePatientFields('p');const mobile=$('pmobile');if(mobile&&!mobile.parentElement.querySelector('.field-help')){const h=document.createElement('div');h.className='field-help';h.textContent='10 digits • used for patient search and follow-up contact';mobile.parentElement.appendChild(h)}const doctor=$('doctor');if(doctor){datalist('doctor-options',DOCTORS);doctor.setAttribute('list','doctor-options');doctor.placeholder='Select or type doctor'}const unit=$('unit');if(unit&&unit.tagName==='SELECT')unit.innerHTML=UNITS.map(x=>`<option>${x}</option>`).join('');const diagnosis=$('diagnosis');if(diagnosis)addListInput('diagnosis',DIAGNOSES);const complaint=$('complaint');if(complaint)complaint.placeholder='e.g. abdominal pain, swelling, wound, vomiting…'}
  function addPatientSearch(prefix){if($(prefix+'-existing-search'))return;const target=$(prefix+'name');if(!target)return;const form=target.closest('form');if(!form)return;const card=document.createElement('div');card.className='smart-search';card.innerHTML=`<div class="smart-title">🔎 Find existing patient</div><div class="smart-row"><input id="${prefix}-existing-search" placeholder="Search name / mobile / OP No. / IP No. / UHID"><button type="button" id="${prefix}-existing-btn">Search</button></div><div id="${prefix}-existing-results"></div>`;const grid=target.closest('.grid');form.insertBefore(card,grid||target.parentElement);$(prefix+'-existing-btn').onclick=async()=>{const q=$(prefix+'-existing-search').value.trim();if(!q)return;const {data,error}=await client.from('patients').select('*').or(`name.ilike.%${q}%,mobile.ilike.%${q}%,hospital_no.ilike.%${q}%,op_no.ilike.%${q}%,ip_no.ilike.%${q}%`).limit(8);if(error){window.toast(error.message);return}$(prefix+'-existing-results').innerHTML=(data||[]).map((p,i)=>`<div class="search-result"><div><b>${esc(p.name)}</b> <span class="pill">${esc(p.op_no||p.ip_no||p.hospital_no||'No ID')}</span><div class="muted">${esc(p.age)} / ${esc(p.sex)} • ${esc(p.mobile||'No mobile')}</div></div><button type="button" data-index="${i}">Use</button></div>`).join('')||'<div class="muted empty">No patient found</div>';$(prefix+'-existing-results').querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>window.usePatient(data[Number(b.dataset.index)]))}}
  function enhanceOTForm(){enhancePatientFields('q');addPatientSearch('q');const proc=$('procedure');if(proc){const kind=(document.querySelector('#view h2')?.textContent||'');addListInput('procedure',kind.includes('Minor')?MINOR_PROCS:kind.includes('Endoscopy')?ENDO_PROCS:MAJOR_PROCS);proc.placeholder='Select or type procedure'}const diagnosis=$('diagnosis');if(diagnosis)addListInput('diagnosis',DIAGNOSES);const doc=$('doctor');if(doc){datalist('doctor-options-ot',DOCTORS);doc.setAttribute('list','doctor-options-ot');doc.placeholder='Select or type consultant'}}
  function filterWaiting(){const rows=[...document.querySelectorAll('#waiting-table-body tr')];const type=($('wait-type-filter')?.value||'All'),status=($('wait-status-filter')?.value||'All'),priority=($('wait-priority-filter')?.value||'All');let visible=0;rows.forEach(r=>{const ok=(type==='All'||r.dataset.type===type)&&(status==='All'||r.dataset.status===status)&&(priority==='All'||r.dataset.priority===priority);r.style.display=ok?'':'none';if(ok)visible++});if($('wait-visible-count'))$('wait-visible-count').textContent=visible}
  function enhanceWaiting(){const heading=document.querySelector('#view h2');if(!heading||heading.textContent!=='Waiting Lists'||$('wait-type-filter'))return;const table=document.querySelector('#view table');if(!table)return;const controls=document.createElement('div');controls.className='filter-bar';controls.innerHTML=`<div class="filter-title">Waiting list filters</div><select id="wait-type-filter"><option>All</option><option>Major OT</option><option>Minor OT</option><option>Endoscopy</option><option>Follow-up</option></select><select id="wait-status-filter"><option>All</option><option>Waiting</option><option>Called</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select><select id="wait-priority-filter"><option>All</option><option>Emergency</option><option>Urgent</option><option>Priority</option><option>Routine</option></select><span class="filter-count"><b id="wait-visible-count">0</b> shown</span>`;table.parentElement.parentElement.insertBefore(controls,table.parentElement);controls.querySelectorAll('select').forEach(x=>x.onchange=filterWaiting);const body=table.querySelector('tbody');body.id='waiting-table-body';[...body.rows].forEach(r=>{const c=r.cells;r.dataset.type=(c[1]?.textContent||'').trim();r.dataset.priority=(c[3]?.textContent||'').trim();r.dataset.status=(c[4]?.textContent||'').trim()});filterWaiting()}
  function improveTables(){document.querySelectorAll('table').forEach(t=>t.classList.add('professional-table'))}
  function observe(){const app=$('app');if(!app)return setTimeout(observe,100);let last='';const run=()=>{const text=app.innerText||'';if(text===last)return;last=text;setTimeout(()=>{enhanceOPD();enhanceOTForm();enhanceWaiting();improveTables()},30)};new MutationObserver(run).observe(app,{childList:true,subtree:true});run()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();
