/* IGMCRI Surgery UI v4 - consolidated fixes: true patient auto-population, mobile fields, clean OPD/Major OT forms, last-tab waiting list, calling-status edit, embedded OT format generator. */
(function(){
'use strict';
const C=window.IGMCRI_CONFIG; if(!C||!window.supabase)return;
const sb4=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey);
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const doctors=['Dr Simon D. Dasiah','Dr Basavanandaswamy','Dr Rayganapathy','Dr Srivengadesh G','Dr Kapil Baliga','Dr Selvakumaran','Dr Ashley Solomon','Dr Mima Maychet Sangma','Dr Ganesan','Dr Govardhanan','Dr Ray'];
const diagnoses=['Cholelithiasis','Acute appendicitis','Inguinal hernia','Incisional hernia','Ventral hernia','Umbilical hernia','Pilonidal sinus','Haemorrhoids','Anal fissure','Fistula-in-ano','Breast lump','Thyroid swelling','Lipoma','Sebaceous cyst','Non-healing ulcer','Wound infection','Thyroid nodule','Gallbladder polyp','Obstructed hernia','Strangulated hernia'];
const majors=['Laparoscopic cholecystectomy','Laparoscopic appendicectomy','Open appendicectomy','Laparoscopic hernia repair','Open hernia repair','Thyroidectomy','Hemithyroidectomy','Modified radical mastectomy','Breast lumpectomy','Colectomy','Bowel resection and anastomosis','Exploratory laparotomy','Incisional hernia repair','Ventral hernia repair','Haemorrhoidectomy','Fistulectomy','Fissurectomy'];
const minors=['Excision biopsy','Incision and drainage','Wound debridement','Suturing','Abscess drainage','Lipoma excision','Sebaceous cyst excision','Nail procedure','Skin lesion excision','Suture removal'];
const endos=['Upper GI endoscopy','Colonoscopy','Flexible sigmoidoscopy','Diagnostic endoscopy','Endoscopic biopsy'];
const wards=['MSW','PSW','Special Ward','SICU','ICU'];
function datalist(id,items){let d=$(id);if(!d){d=document.createElement('datalist');d.id=id;document.body.appendChild(d)}d.innerHTML=items.map(x=>`<option value="${esc(x)}"></option>`).join('');return id}
function suggest(id,items,key){const e=$(id);if(!e||e.tagName==='SELECT')return;e.setAttribute('list',datalist(key,items));e.setAttribute('autocomplete','off')}
function fill(prefix,p){if(!p)return;const map={name:'name',hno:'hospital_no',opno:'op_no',ipno:'ip_no',age:'age',sex:'sex',mobile:'mobile',mobile2:'mobile_2',bg:'blood_group'};Object.entries(map).forEach(([id,k])=>{const e=$(prefix+id);if(e)e.value=p[k]??''});}
function removeField(id){const e=$(id);if(e)e.closest('div')?.remove()}
function cleanPatient(prefix){['address'].forEach(k=>removeField(prefix+k));const m=$(prefix+'mobile');if(m){m.type='tel';m.inputMode='numeric';m.maxLength=10;m.placeholder='10-digit mobile number';if(!m.dataset.v4){m.dataset.v4='1';m.addEventListener('input',()=>m.value=m.value.replace(/\D/g,'').slice(0,10))}}
  if(!$(`${prefix}mobile2`)&&m){const wrap=document.createElement('div');wrap.innerHTML=`<label>Mobile number 2</label><input id="${prefix}mobile2" type="tel" inputmode="numeric" maxlength="10" placeholder="10-digit mobile number" autocomplete="tel">`;m.closest('div').insertAdjacentElement('afterend',wrap.firstElementChild.parentElement);const n=$(`${prefix}mobile2`);n.addEventListener('input',()=>n.value=n.value.replace(/\D/g,'').slice(0,10))}}
function removeOPDExtras(){['complaint','exam','pr','bp','spo2','temp'].forEach(removeField);const diag=$('diagnosis');if(diag){diag.outerHTML=`<div class="wide"><label>Diagnosis</label><input id="diagnosis" list="v4-diagnoses" placeholder="Select or type diagnosis"></div>`;suggest('diagnosis',diagnoses,'v4-diagnoses')}if(!$('laterality')){const plan=$('plan');if(plan){const x=document.createElement('div');x.innerHTML='<label>Laterality</label><select id="laterality"><option>Not applicable</option><option>Right</option><option>Left</option><option>Bilateral</option><option>Midline</option></select>';plan.closest('div')?.insertAdjacentElement('beforebegin',x.firstElementChild.parentElement)}}}
function addSearch(prefix){if($(`${prefix}v4search`))return;const target=$(prefix+'name');if(!target)return;const form=target.closest('form');if(!form)return;const card=document.createElement('div');card.className='card';card.style.background='#f7fafc';card.innerHTML=`<label><b>Find existing patient</b></label><div class="actions"><input id="${prefix}v4search" placeholder="Name / mobile / OP No. / IP No. / UHID"><button type="button" id="${prefix}v4searchbtn">Search</button></div><div id="${prefix}v4results"></div>`;form.insertBefore(card,form.querySelector('.grid')||form.firstChild);$(`${prefix}v4searchbtn`).onclick=()=>search(prefix);$(`${prefix}v4search`).onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search(prefix)}}}
async function search(prefix){const q=($(`${prefix}v4search`)?.value||'').trim();if(!q)return;const {data,error}=await sb4.from('patients').select('*').or(`name.ilike.%${q}%,mobile.ilike.%${q}%,mobile_2.ilike.%${q}%,hospital_no.ilike.%${q}%,op_no.ilike.%${q}%,ip_no.ilike.%${q}%`).limit(8);if(error){window.toast?.(error.message);return}const box=$(`${prefix}v4results`);box.innerHTML=(data||[]).map((p,i)=>`<div class="search-result" style="display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-top:1px solid #e2e8f0"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.op_no||p.ip_no||p.hospital_no||'')} • ${esc(p.mobile||'')}${p.mobile_2?' • '+esc(p.mobile_2):''}</div></div><button type="button" data-i="${i}">Use</button></div>`).join('')||'<div class="muted">No patient found</div>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>window.usePatient((data||[])[+b.dataset.i]));}
const originalUse=window.usePatient;
window.usePatient=function(p){try{originalUse?.(p)}catch{}window.__v4patient=p;if($('pname')){fill('p',p);window.toast?.('Existing patient selected — details auto-populated')}if($('qname')){fill('q',p);window.toast?.('Existing patient selected — details auto-populated')}};
function addOTFields(){cleanPatient('q');const h=document.querySelector('#view h2')?.textContent||'';suggest('doctor',doctors,'v4-doctors');suggest('diagnosis',diagnoses,'v4-diagnoses');suggest('procedure',h.includes('Minor')?minors:h.includes('Endoscopy')?endos:majors,'v4-procedures');const w=$('ward');if(w&&w.tagName!=='SELECT'){const s=document.createElement('select');s.id='ward';s.innerHTML='<option value="">Select ward</option>'+wards.map(x=>`<option>${x}</option>`).join('');w.replaceWith(s)}if(h.includes('Major')){const p=$('procedure');if(p&&!$('availability')){const x=document.createElement('div');x.innerHTML='<label>Availability</label><select id="availability"><option value="">Select</option><option>Available</option><option>Not available</option><option>Awaiting clearance</option><option>To be confirmed</option></select>';p.closest('div')?.insertAdjacentElement('afterend',x.firstElementChild.parentElement)}if(p&&!$('laterality')){const x=document.createElement('div');x.innerHTML='<label>Laterality</label><select id="laterality"><option>Not applicable</option><option>Right</option><option>Left</option><option>Bilateral</option><option>Midline</option></select>';p.closest('div')?.insertAdjacentElement('afterend',x.firstElementChild.parentElement)}}}
function removeOTAddress(){removeField('qaddress')}
async function renderWaiting(){const v=$('view');if(!v)return;const d=$('wdate')?.value||today();const {data,error}=await sb4.from('waiting_list').select('*,patients(name,age,sex,op_no,ip_no,mobile,mobile_2)').eq('list_date',d).order('source_type').order('priority').order('sequence_no');if(error){window.toast?.(error.message);return}v.innerHTML=`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><h2 style="margin:0">Waiting Lists</h2><input id="wdate" type="date" value="${d}"></div><div class="filter-bar" style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0"><select id="v4type"><option>All</option><option>Major OT</option><option>Minor OT</option><option>Endoscopy</option><option>Follow-up</option></select><select id="v4priority"><option>All priorities</option><option>Emergency</option><option>Urgent</option><option>Priority</option><option>Routine</option></select><select id="v4call"><option>All calling responses</option><option>Responded - Willing to come</option><option>Responded - Not willing</option><option>Not reachable</option><option>Not called</option></select><select id="v4status"><option>All statuses</option><option>Waiting</option><option>Called</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select></div><div class="tablewrap"><table class="table"><thead><tr><th>#</th><th>List</th><th>Patient</th><th>Mobile 1</th><th>Mobile 2</th><th>Priority</th><th>Calling response</th><th>Status</th><th>Edit</th></tr></thead><tbody id="v4tbody">${(data||[]).map(r=>row(r)).join('')}</tbody></table></div></div>`;$('wdate').onchange=()=>renderWaiting();['v4type','v4priority','v4call','v4status'].forEach(id=>$(id).onchange=filterRows);filterRows()}
function row(r){return `<tr data-type="${esc(r.source_type)}" data-priority="${esc(r.priority||'Routine')}" data-call="${esc(r.call_status||'Not called')}" data-status="${esc(r.status||'Waiting')}"><td>${r.sequence_no||''}</td><td>${esc(r.source_type)}</td><td><b>${esc(r.patients?.name||'')}</b><br>${esc(r.patients?.op_no||r.patients?.ip_no||'')}</td><td>${esc(r.patients?.mobile||'')}</td><td>${esc(r.patients?.mobile_2||'')}</td><td>${esc(r.priority||'Routine')}</td><td><select data-call-id="${r.id}"><option>Not called</option><option ${r.call_status==='Responded - Willing to come'?'selected':''}>Responded - Willing to come</option><option ${r.call_status==='Responded - Not willing'?'selected':''}>Responded - Not willing</option><option ${r.call_status==='Not reachable'?'selected':''}>Not reachable</option></select></td><td>${esc(r.status||'Waiting')}</td><td><button type="button" data-edit="${r.id}">Edit</button></td></tr>`}
function filterRows(){const t=$('v4type')?.value,p=$('v4priority')?.value,c=$('v4call')?.value,s=$('v4status')?.value;document.querySelectorAll('#v4tbody tr').forEach(r=>r.style.display=((!t||t==='All'||r.dataset.type===t)&&(!p||p==='All priorities'||r.dataset.priority===p)&&(!c||c==='All calling responses'||r.dataset.call===c)&&(!s||s==='All statuses'||r.dataset.status===s))?'':'none');document.querySelectorAll('[data-call-id]').forEach(sel=>sel.onchange=async()=>{await sb4.from('waiting_list').update({call_status:sel.value,edited_at:new Date().toISOString()}).eq('id',sel.dataset.callId);const tr=sel.closest('tr');tr.dataset.call=sel.value;filterRows()});document.querySelectorAll('[data-edit]').forEach(btn=>btn.onclick=()=>editWaiting(btn.dataset.edit))}
async function editWaiting(id){const {data}=await sb4.from('waiting_list').select('*,patients(*)').eq('id',id).single();if(!data)return;const p=data.patients||{};const box=document.createElement('div');box.style='position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;padding:16px;z-index:9999';box.innerHTML=`<div style="background:#fff;max-width:520px;width:100%;padding:18px;border-radius:14px"><h3>Edit waiting-list patient</h3><p><b>${esc(p.name||'')}</b></p><label>Mobile 1</label><input id="e_m1" value="${esc(p.mobile||'')}"><label>Mobile 2</label><input id="e_m2" value="${esc(p.mobile_2||'')}"><label>Priority</label><select id="e_pr"><option ${data.priority==='Routine'?'selected':''}>Routine</option><option ${data.priority==='Priority'?'selected':''}>Priority</option><option ${data.priority==='Urgent'?'selected':''}>Urgent</option><option ${data.priority==='Emergency'?'selected':''}>Emergency</option></select><label>Calling response</label><select id="e_call"><option ${data.call_status==='Not called'?'selected':''}>Not called</option><option ${data.call_status==='Responded - Willing to come'?'selected':''}>Responded - Willing to come</option><option ${data.call_status==='Responded - Not willing'?'selected':''}>Responded - Not willing</option><option ${data.call_status==='Not reachable'?'selected':''}>Not reachable</option></select><label>Notes</label><textarea id="e_notes">${esc(data.notes||'')}</textarea><div class="actions" style="margin-top:12px"><button id="e_save">Save</button><button id="e_cancel" type="button" class="secondary">Cancel</button></div></div>`;document.body.appendChild(box);$('e_cancel').onclick=()=>box.remove();$('e_save').onclick=async()=>{await sb4.from('patients').update({mobile:$('e_m1').value,mobile_2:$('e_m2').value}).eq('id',p.id);await sb4.from('waiting_list').update({priority:$('e_pr').value,call_status:$('e_call').value,notes:$('e_notes').value,edited_at:new Date().toISOString()}).eq('id',id);box.remove();renderWaiting()}}
function embedGenerator(){const v=$('view');if(!v)return;v.innerHTML='<div style="background:#fff;border-radius:14px;overflow:hidden"><iframe src="ot-generator.html?v=20260817-v5" style="width:100%;height:calc(100vh - 170px);min-height:820px;border:0" title="IGMCRI OT List Generator"></iframe></div>'}
function run(){const view=$('view');if(!view)return;const h=view.querySelector('h2')?.textContent||'';const txt=view.innerText||'';if(txt.includes('OPD Patient Registration')){cleanPatient('p');removeOPDExtras();addSearch('p');suggest('doctor',doctors,'v4-doctors')}if(/Major OT Registration|Minor OT Registration|Endoscopy Registration/.test(h)){cleanPatient('q');removeOTAddress();addSearch('q');addOTFields()}if(h==='Waiting Lists'){const nav=document.querySelector('.nav');const b=[...document.querySelectorAll('.nav button')].find(x=>x.textContent.includes('Waiting Lists'));if(nav&&b)nav.appendChild(b);if(!v4WaitingLock){v4WaitingLock=true;renderWaiting()}}if(txt.includes('OT List Generator')&&h!=='Waiting Lists'&&window.__v4Embed!==true){/* nav button handler replacement below */}}
let v4WaitingLock=false;let v4Timer;function schedule(){clearTimeout(v4Timer);v4Timer=setTimeout(run,100)}
const app=$('app')||document.body;new MutationObserver(()=>{v4WaitingLock=false;schedule()}).observe(app,{childList:true,subtree:true});
const originalGo=window.go;window.go=function(t){if(t==='ot'){tab='ot';window.__v4Embed=true;embedGenerator();return originalGo?.(t)}window.__v4Embed=false;v4WaitingLock=false;return originalGo?.(t)};
schedule();
})();
