/* IGMCRI Surgery UI v3 - stable, non-invasive interface enhancements. */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const doctors=['Dr Simon D. Dasiah','Dr Basavanandaswamy','Dr Rayganapathy','Dr Srivengadesh G','Dr Kapil Baliga','Dr Selvakumaran','Dr Ashley Solomon','Dr Mima Maychet Sangma','Dr Ganesan','Dr Govardhanan','Dr Ray'];
  const units=['S1','S2','S3','S4','S5','S6'];
  const major=['Laparoscopic cholecystectomy','Laparoscopic appendicectomy','Open appendicectomy','Laparoscopic hernia repair','Open hernia repair','Thyroidectomy','Hemithyroidectomy','Modified radical mastectomy','Breast lumpectomy','Colectomy','Bowel resection and anastomosis','Exploratory laparotomy','Incisional hernia repair','Ventral hernia repair','Haemorrhoidectomy','Fistulectomy','Fissurectomy'];
  const minor=['Excision biopsy','Incision and drainage','Wound debridement','Suturing','Abscess drainage','Lipoma excision','Sebaceous cyst excision','Nail procedure','Skin lesion excision','Suture removal'];
  const endo=['Upper GI endoscopy','Colonoscopy','Flexible sigmoidoscopy','Diagnostic endoscopy','Endoscopic biopsy'];
  const diagnoses=['Cholelithiasis','Acute appendicitis','Inguinal hernia','Incisional hernia','Ventral hernia','Umbilical hernia','Pilonidal sinus','Haemorrhoids','Anal fissure','Fistula-in-ano','Breast lump','Thyroid swelling','Lipoma','Sebaceous cyst','Non-healing ulcer','Wound infection'];
  function list(id,items){let d=$(id);if(!d){d=document.createElement('datalist');d.id=id;document.body.appendChild(d)}d.innerHTML=items.map(x=>`<option value="${esc(x)}"></option>`).join('');return id}
  function suggest(el,items,id){if(!el)return;el.setAttribute('list',list(id,items));el.setAttribute('autocomplete','off')}
  function fieldAfter(el,label,id){if(!el||$(id))return;const wrap=document.createElement('div');wrap.innerHTML=`<label>${label}</label><input id="${id}" type="tel" inputmode="numeric" maxlength="10" placeholder="10-digit mobile number" autocomplete="tel">`;el.parentElement.parentElement.insertAdjacentElement('afterend',wrap.firstElementChild.parentElement);const input=$(id);input.addEventListener('input',()=>input.value=input.value.replace(/\D/g,'').slice(0,10))}
  function hideAddress(prefix){const a=$(prefix+'address');if(a)a.closest('div')?.remove()}
  function addSecondMobile(prefix){const m=$(prefix+'mobile');if(!m||$(prefix+'mobile2'))return;const wrap=document.createElement('div');wrap.innerHTML=`<label>Mobile number 2</label><input id="${prefix}mobile2" type="tel" inputmode="numeric" maxlength="10" placeholder="10-digit mobile number" autocomplete="tel">`;m.closest('div').insertAdjacentElement('afterend',wrap.firstElementChild.parentElement);const input=$(prefix+'mobile2');input.addEventListener('input',()=>input.value=input.value.replace(/\D/g,'').slice(0,10))}
  function addPatientExtras(prefix){const m=$(prefix+'mobile');if(m){m.type='tel';m.inputMode='numeric';m.maxLength=10;m.placeholder='10-digit mobile number';m.addEventListener('input',()=>m.value=m.value.replace(/\D/g,'').slice(0,10),{once:true})}addSecondMobile(prefix);hideAddress(prefix)}
  function opd(){addPatientExtras('p');suggest($('doctor'),doctors,'v3-doctors');suggest($('diagnosis'),diagnoses,'v3-diagnoses');const nav=[...document.querySelectorAll('.nav button')];nav.forEach(b=>{if(b.textContent.includes('Waiting Lists'))b.title='Filter: Major OT / Minor OT / Endoscopy / Follow-up'});}
  function ot(){addPatientExtras('q');const h=document.querySelector('#view h2')?.textContent||'';suggest($('doctor'),doctors,'v3-ot-doctors');suggest($('diagnosis'),diagnoses,'v3-ot-diagnoses');suggest($('procedure'),h.includes('Minor')?minor:h.includes('Endoscopy')?endo:major,'v3-procedures');const ward=$('ward');if(ward&&ward.tagName!=='SELECT'){const s=document.createElement('select');s.id='ward';s.innerHTML='<option value="">Select ward</option><option>MSW</option><option>PSW</option><option>Special Ward</option><option>SICU</option><option>ICU</option>';ward.replaceWith(s)}if(h.includes('Major')){const proc=$('procedure');if(proc&&!$('availability')){const box=proc.closest('div');const extra=document.createElement('div');extra.innerHTML='<label>Availability</label><select id="availability"><option value="">Select</option><option>Available</option><option>Not available</option><option>Awaiting clearance</option><option>To be confirmed</option></select>';box.insertAdjacentElement('afterend',extra.firstElementChild.parentElement)}if(proc&&!$('laterality')){const box=proc.closest('div');const extra=document.createElement('div');extra.innerHTML='<label>Laterality</label><select id="laterality"><option value="">Not applicable</option><option>Right</option><option>Left</option><option>Bilateral</option><option>Midline</option></select>';box.insertAdjacentElement('afterend',extra.firstElementChild.parentElement)}}}
  function reorderWaiting(){const nav=document.querySelector('.nav');if(!nav)return;const b=[...nav.children].find(x=>x.textContent.includes('Waiting Lists'));if(b)nav.appendChild(b)}
  function waiting(){reorderWaiting();const view=$('view');if(!view||view.dataset.v3waiting==='1')return;const heading=view.querySelector('h2');if(!heading||heading.textContent!=='Waiting Lists')return;view.dataset.v3waiting='1';const card=heading.closest('.card');const top=document.createElement('div');top.className='filter-bar';top.innerHTML='<strong>Waiting List</strong><select id="v3type"><option>All</option><option>Major OT</option><option>Minor OT</option><option>Endoscopy</option><option>Follow-up</option></select><select id="v3status"><option>All statuses</option><option>Waiting</option><option>Called</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select><select id="v3call"><option>All calling responses</option><option>Responded - Willing to come</option><option>Responded - Not willing</option><option>Not reachable</option></select>';card.insertBefore(top,card.children[1]||null);top.querySelectorAll('select').forEach(s=>s.addEventListener('change',()=>filterWaiting(view)));filterWaiting(view)}
  function filterWaiting(view){const rows=[...view.querySelectorAll('tbody tr')];const type=$('v3type')?.value||'All',status=$('v3status')?.value||'All';rows.forEach(r=>{const t=r.textContent;const okType=type==='All'||t.includes(type);const okStatus=status==='All statuses'||t.includes(status);r.style.display=okType&&okStatus?'':'none'});}
  function run(){const app=$('app');if(!app)return;const text=app.innerText||'';if(text.includes('OPD Patient Registration'))opd();if(/^(Major OT|Minor OT|Endoscopy) Registration/.test(text.split('\n')[1]||''))ot();if(text.includes('Waiting Lists'))waiting();}
  let timer;function schedule(){clearTimeout(timer);timer=setTimeout(run,80)}
  const app=$('app')||document.body;new MutationObserver(schedule).observe(app,{childList:true,subtree:true});schedule();
})();
