/* IGMCRI Surgery UI v2 — clinician-focused mobile OPD / Major OT / Waiting List */
(function(){
  const client=supabase.createClient(IGMCRI_CONFIG.supabaseUrl,IGMCRI_CONFIG.supabasePublishableKey);
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const today=()=>new Date().toISOString().slice(0,10);
  const toast=m=>window.toast?window.toast(m):alert(m);
  const DOCTORS=['Dr Simon D. Dasiah','Dr Basavanandaswamy','Dr Rayganapathy','Dr Srivengadesh G','Dr Kapil Baliga','Dr Selvakumaran','Dr Ashley Solomon','Dr Mima Maychet Sangma','Dr Ganesan','Dr Govardhanan','Dr Ray'];
  const DIAGNOSES=['Cholelithiasis','Acute appendicitis','Inguinal hernia','Incisional hernia','Ventral hernia','Umbilical hernia','Pilonidal sinus','Haemorrhoids','Anal fissure','Fistula-in-ano','Breast lump','Thyroid swelling','Lipoma','Sebaceous cyst','Non-healing ulcer','Wound infection','Thyroid nodule','Gallbladder polyp','Obstructed hernia','Strangulated hernia'];
  const MAJOR_PROCS=['Laparoscopic cholecystectomy','Laparoscopic appendicectomy','Open appendicectomy','Laparoscopic hernia repair','Open hernia repair','Thyroidectomy','Hemithyroidectomy','Modified radical mastectomy','Breast lumpectomy','Colectomy','Bowel resection and anastomosis','Exploratory laparotomy','Incisional hernia repair','Ventral hernia repair','Haemorrhoidectomy','Fistulectomy','Fissurectomy'];
  const WARDS=['MSW','PSW','Special Ward','SICU','ICU'];
  const CALL=['Not called','Responded – Willing to come','Responded – Not willing','Not reachable'];
  const addCss=()=>{if($('ui-v2-css'))return;const s=document.createElement('style');s.id='ui-v2-css';s.textContent=`
    .v2-card{background:#fff;border:1px solid #dfe7ef;border-radius:16px;padding:16px;box-shadow:0 4px 18px rgba(16,42,67,.06);margin-bottom:14px}
    .v2-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.v2-title h2{margin:0;font-size:21px}.v2-sub{color:#667085;font-size:12px}
    .v2-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.v2-wide{grid-column:1/-1}
    .v2-grid label{font-size:12px;font-weight:800;color:#344054;margin-bottom:5px;display:block}.v2-grid input,.v2-grid select,.v2-grid textarea{width:100%;padding:11px 12px;border:1px solid #cfd8e3;border-radius:10px;background:#fff;font:inherit}.v2-grid textarea{min-height:78px}
    .v2-search{background:#f7fafc;border:1px solid #e4eaf0;border-radius:14px;padding:12px;margin-bottom:14px}.v2-search-row{display:flex;gap:8px}.v2-search-row input{flex:1}.v2-search-row button{white-space:nowrap}.v2-result{display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px solid #e7edf3;padding:10px 0}.v2-result:first-child{margin-top:8px}
    .v2-patient-strip{display:grid;grid-template-columns:1.3fr .8fr .8fr .9fr;gap:10px;padding:12px;border-radius:12px;background:#f7fafc;margin-bottom:14px}.v2-patient-strip b{display:block}.v2-small{font-size:12px;color:#667085}
    .v2-checks{display:flex;gap:8px;flex-wrap:wrap}.v2-check{padding:8px 11px;border:1px solid #d6dee8;border-radius:999px;background:#f8fafc;font-size:12px;font-weight:700}
    .v2-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.v2-actions button{min-height:42px}
    .v2-filters{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:9px;margin:12px 0}.v2-filters label{font-size:11px;font-weight:800;color:#475467}.v2-table{width:100%;border-collapse:separate;border-spacing:0;font-size:13px}.v2-table th{background:#f4f7fa;font-size:11px;text-transform:uppercase;letter-spacing:.03em;color:#475467}.v2-table th,.v2-table td{padding:10px;border-bottom:1px solid #e7edf3;text-align:left;vertical-align:top}.v2-table tr:hover td{background:#fbfdff}.v2-mobile{white-space:nowrap}.v2-call{min-width:210px}.v2-status{font-weight:700}.v2-empty{text-align:center;padding:30px;color:#667085}.v2-modal{position:fixed;inset:0;background:rgba(15,23,42,.48);display:flex;align-items:center;justify-content:center;padding:16px;z-index:100}.v2-modal-box{width:min(560px,100%);background:#fff;border-radius:18px;padding:18px;box-shadow:0 20px 60px rgba(0,0,0,.2)}
    .v2-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#edf5fa;font-size:11px;font-weight:800}.v2-ok{background:#eaf7ef;color:#166534}.v2-warn{background:#fff7e6;color:#92400e}.v2-danger{background:#fff0f0;color:#991b1b}
    @media(max-width:750px){.v2-grid,.v2-filters,.v2-patient-strip{grid-template-columns:1fr}.v2-wide{grid-column:auto}.v2-search-row{flex-direction:column}.v2-table{min-width:980px}.v2-table-wrap{overflow:auto}.v2-card{padding:13px}.v2-title h2{font-size:18px}}
  `;document.head.appendChild(s)};
  const datalist=(id,items)=>{if($(id))return;const d=document.createElement('datalist');d.id=id;d.innerHTML=items.map(x=>`<option value="${esc(x)}">`).join('');document.body.appendChild(d)};
  const field=(label,id,type='text',extra='')=>`<div><label>${label}</label><input id="${id}" type="${type}" ${extra}></div>`;
  const patientForm=(prefix='p')=>`<div class="v2-grid">
    ${field('Patient name *',prefix+'name','text','required autocomplete="name"')}
    ${field('Hospital / UHID No.',prefix+'hno')}
    ${field('OP No.',prefix+'opno')}
    ${field('IP No.',prefix+'ipno')}
    ${field('Age',prefix+'age','number','min="0" max="130"')}
    <div><label>Sex</label><select id="${prefix}sex"><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></div>
    ${field('Mobile No. 1',prefix+'mobile','tel','inputmode="numeric" maxlength="10"')}
    ${field('Mobile No. 2',prefix+'mobile2','tel','inputmode="numeric" maxlength="10"')}
    <div><label>Blood group</label><select id="${prefix}bg"><option value="">Select</option>${['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=>`<option>${x}</option>`).join('')}</select></div>
  </div>`;
  function mobileRules(prefix){['mobile','mobile2'].forEach(k=>{const e=$(prefix+k);if(e&&!e.dataset.v2){e.dataset.v2='1';e.addEventListener('input',()=>e.value=e.value.replace(/\D/g,'').slice(0,10));}})}
  function fillPatient(p,prefix){if(!p)return;['name','hospital_no','op_no','ip_no','age','sex','mobile','mobile_2','blood_group'].forEach(k=>{const id=prefix+({hospital_no:'hno',op_no:'opno',mobile_2:'mobile2',blood_group:'bg'}[k]||k);if($(id))$(id).value=p[k]??''});window.__v2Patient=p;}
  async function searchPatients(q){if(!q)return[];const {data,error}=await client.from('patients').select('*').or(`name.ilike.%${q}%,mobile.ilike.%${q}%,mobile_2.ilike.%${q}%,hospital_no.ilike.%${q}%,op_no.ilike.%${q}%,ip_no.ilike.%${q}%`).limit(8);if(error)throw error;return data||[]}
  async function patientSearch(prefix){const q=$(prefix+'-search').value.trim();if(!q)return;try{const data=await searchPatients(q);const box=$(prefix+'-results');box.innerHTML=data.map((p,i)=>`<div class="v2-result"><div><b>${esc(p.name)}</b> <span class="v2-pill">${esc(p.op_no||p.ip_no||p.hospital_no||'No ID')}</span><div class="v2-small">${esc(p.age)} / ${esc(p.sex)} • ${esc(p.mobile||'No mobile')}${p.mobile_2?' • '+esc(p.mobile_2):''}</div></div><button type="button" data-i="${i}">Use</button></div>`).join('')||'<div class="v2-empty">No patient found.</div>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{fillPatient(data[+b.dataset.i],prefix);box.innerHTML='<div class="v2-pill v2-ok">✓ Existing patient selected — details auto-populated</div>';});}catch(e){toast(e.message)}}
  const searchBox=(prefix)=>`<div class="v2-search"><b>Find existing patient</b><div class="v2-sub">Search by name, mobile number, OP/IP number or UHID</div><div class="v2-search-row" style="margin-top:8px"><input id="${prefix}-search" placeholder="Search patient…"><button type="button" id="${prefix}-search-btn">Search</button></div><div id="${prefix}-results"></div></div>`;
  async function saveOrUpdatePatient(prefix){
    const existing=window.__v2Patient&&window.__v2Patient.id?window.__v2Patient:null;
    const p={name:$(prefix+'name').value.trim(),hospital_no:$(prefix+'hno').value||null,op_no:$(prefix+'opno').value||null,ip_no:$(prefix+'ipno').value||null,age:Number($(prefix+'age').value)||null,sex:$(prefix+'sex').value||null,mobile:$(prefix+'mobile').value||null,mobile_2:$(prefix+'mobile2').value||null,blood_group:$(prefix+'bg').value||null};
    if(!p.name)throw Error('Patient name is required');
    let r=existing?await client.from('patients').update(p).eq('id',existing.id).select().single():await client.from('patients').insert(p).select().single();
    if(r.error&&r.error.code==='23505'&&p.hospital_no){r=await client.from('patients').select('*').eq('hospital_no',p.hospital_no).single();}
    if(r.error)throw r.error;window.__v2Patient=r.data;return r.data;
  }
  function installCommon(prefix){mobileRules(prefix);datalist('v2-doctors',DOCTORS);datalist('v2-diagnoses',DIAGNOSES);}
  async function renderOPD(v){
    window.__v2Patient=null;v.innerHTML=`<div class="v2-card"><div class="v2-title"><div><h2>OPD Registration</h2><div class="v2-sub">Patient registration & surgical assessment</div></div><span class="v2-pill">Mobile friendly</span></div>${searchBox('p')}<form id="v2-opd-form">${patientForm('p')}<div class="v2-grid" style="margin-top:12px">
      <div><label>Visit type</label><select id="v2-vtype"><option>New</option><option>Follow-up</option><option>Post-op</option><option>Referral</option></select></div>
      <div><label>Unit</label><select id="v2-unit">${['S1','S2','S3','S4','S5','S6'].map(x=>`<option>${x}</option>`).join('')}</select></div>
      <div><label>Doctor</label><input id="v2-doctor" list="v2-doctors" placeholder="Select / type doctor"></div>
      <div><label>Visit date</label><input id="v2-date" type="date" value="${today()}"></div>
      <div><label>Diagnosis</label><input id="v2-diagnosis" list="v2-diagnoses" placeholder="Select / type diagnosis"></div>
      <div><label>Laterality</label><select id="v2-laterality"><option>Not applicable</option><option>Right</option><option>Left</option><option>Bilateral</option><option>Midline</option></select></div>
      <div class="v2-wide"><label>Plan / Advice</label><textarea id="v2-plan" placeholder="Plan, investigations, treatment, follow-up advice…"></textarea></div>
      <div class="v2-wide"><label>Add to waiting list</label><div class="v2-checks"><label class="v2-check"><input type="checkbox" id="v2-major"> Major OT</label><label class="v2-check"><input type="checkbox" id="v2-minor"> Minor OT</label><label class="v2-check"><input type="checkbox" id="v2-endo"> Endoscopy</label><label class="v2-check"><input type="checkbox" id="v2-follow"> Follow-up</label></div></div>
    </div><div class="v2-actions"><button type="submit">Save OPD Visit</button><button type="button" class="secondary" onclick="window.go('dashboard')">Cancel</button></div></form></div>`;
    installCommon('p');$('p-search-btn').onclick=()=>patientSearch('p');$('p-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();patientSearch('p')}};
    $('v2-opd-form').onsubmit=async e=>{e.preventDefault();try{const p=await saveOrUpdatePatient('p');const cross=[];if($('v2-major').checked)cross.push('Major OT');if($('v2-minor').checked)cross.push('Minor OT');if($('v2-endo').checked)cross.push('Endoscopy');if($('v2-follow').checked)cross.push('Follow-up');const payload={patient_id:p.id,visit_date:$('v2-date').value,unit:$('v2-unit').value,doctor:$('v2-doctor').value,visit_type:$('v2-vtype').value,provisional_diagnosis:$('v2-diagnosis').value,plan:$('v2-plan').value,cross_added_to:cross,created_by:window.user?.id||null};const r=await client.from('opd_visits').insert(payload);if(r.error)throw r.error;for(const type of cross){const seq=(await client.rpc('next_waiting_sequence',{p_date:payload.visit_date,p_source:type})).data;await client.from('waiting_list').insert({patient_id:p.id,source_type:type,list_date:payload.visit_date,sequence_no:seq,call_status:'Not called',created_by:window.user?.id||null});}toast('OPD visit saved');window.__v2Patient=null;window.go('dashboard')}catch(x){toast(x.message)}};
  }
  async function renderMajor(v){
    window.__v2Patient=null;v.innerHTML=`<div class="v2-card"><div class="v2-title"><div><h2>Major OT Registration</h2><div class="v2-sub">Surgical planning & pre-operative list</div></div><span class="v2-pill">Major OT</span></div>${searchBox('q')}<form id="v2-major-form">${patientForm('q')}<div class="v2-grid" style="margin-top:12px">
      <div><label>Priority</label><select id="v2-priority"><option>Routine</option><option>Priority</option><option>Urgent</option><option>Emergency</option></select></div>
      <div><label>Planned date</label><input id="v2-date" type="date" value="${today()}"></div>
      <div><label>Surgeon</label><input id="v2-surgeon" list="v2-doctors" placeholder="Select / type surgeon"></div>
      <div><label>OP / IP No.</label><input id="v2-opip"></div>
      <div><label>Ward</label><select id="v2-ward">${WARDS.map(x=>`<option>${x}</option>`).join('')}</select></div>
      <div><label>Procedure</label><input id="v2-procedure" list="v2-major-procs" placeholder="Select / type procedure" required></div>
      <div><label>Availability</label><select id="v2-availability"><option>To be confirmed</option><option>Available</option><option>Not available</option></select></div>
      <div><label>Laterality</label><select id="v2-laterality"><option>Not applicable</option><option>Right</option><option>Left</option><option>Bilateral</option><option>Midline</option></select></div>
      <div class="v2-wide"><label>Diagnosis</label><input id="v2-diagnosis" list="v2-diagnoses" placeholder="Select / type diagnosis"></div>
      <div class="v2-wide"><label>Remarks</label><textarea id="v2-remarks"></textarea></div>
    </div><details style="margin-top:12px"><summary>Pre-operative details</summary><div class="v2-grid" style="margin-top:12px">
      <div><label>Anesthesia type</label><select id="v2-anesthesia"><option></option><option>GA</option><option>SA</option><option>LA</option><option>Regional</option><option>Other</option></select></div><div><label>ASA grade</label><select id="v2-asa"><option></option><option>I</option><option>II</option><option>III</option><option>IV</option><option>V</option></select></div>
      <div><label>Anesthesia fitness</label><select id="v2-fitness"><option></option><option>Fit</option><option>Not fit</option><option>Pending</option></select></div><div class="v2-wide"><label>Investigation status</label><textarea id="v2-investigations" placeholder="ECG / CXR / blood investigations / other pending work-up"></textarea></div>
    </div></details><div class="v2-actions"><button type="submit">Save Major OT</button><button type="button" class="secondary" onclick="window.go('dashboard')">Cancel</button></div></form></div>`;
    datalist('v2-doctors',DOCTORS);datalist('v2-diagnoses',DIAGNOSES);datalist('v2-major-procs',MAJOR_PROCS);installCommon('q');$('q-search-btn').onclick=()=>patientSearch('q');$('q-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();patientSearch('q')}};
    $('v2-major-form').onsubmit=async e=>{e.preventDefault();try{const p=await saveOrUpdatePatient('q');const date=$('v2-date').value;const payload={patient_id:p.id,priority:$('v2-priority').value,remarks:$('v2-remarks').value,created_by:window.user?.id||null,tentative_date:date,planned_procedure:$('v2-procedure').value,diagnosis:$('v2-diagnosis').value,surgeon:$('v2-surgeon').value,op_ip_no:$('v2-opip').value,ward_bed:$('v2-ward').value,anesthesia_type:$('v2-anesthesia').value,asa_grade:$('v2-asa').value,anesthesia_fitness:$('v2-fitness').value,investigation_status:$('v2-investigations').value,availability:$('v2-availability').value,laterality:$('v2-laterality').value};const r=await client.from('major_ot_list').insert(payload).select().single();if(r.error)throw r.error;const seq=(await client.rpc('next_waiting_sequence',{p_date:date,p_source:'Major OT'})).data;await client.from('waiting_list').insert({patient_id:p.id,source_type:'Major OT',list_date:date,priority:payload.priority,sequence_no:seq,source_id:r.data.id,call_status:'Not called',created_by:window.user?.id||null});toast('Major OT saved');window.__v2Patient=null;window.go('waiting')}catch(x){toast(x.message)}};
  }
  async function renderWaiting(v){
    const d=$('wdate')?.value||today();const {data,error}=await client.from('waiting_list').select('*,patients(name,age,sex,op_no,ip_no,mobile,mobile_2)').eq('list_date',d).order('source_type').order('priority').order('sequence_no');if(error){toast(error.message);return}
    const rows=data||[];v.innerHTML=`<div class="v2-card"><div class="v2-title"><div><h2>Waiting Lists</h2><div class="v2-sub">Calling, response tracking and list management</div></div><span class="v2-pill">${rows.length} total</span></div><div class="v2-filters"><div><label>Date</label><input id="wdate" type="date" value="${d}"></div><div><label>List</label><select id="v2-type"><option>All</option><option>Major OT</option><option>Minor OT</option><option>Endoscopy</option><option>Follow-up</option></select></div><div><label>Call status</label><select id="v2-call-filter"><option>All</option>${CALL.map(x=>`<option>${x}</option>`).join('')}</select></div><div style="align-self:end"><button type="button" id="v2-refresh">Refresh</button></div></div><div class="v2-table-wrap"><table class="v2-table"><thead><tr><th>#</th><th>List</th><th>Patient</th><th>Mobile numbers</th><th>Priority</th><th>Calling status</th><th>Action</th></tr></thead><tbody id="v2-wbody">${rows.map(x=>`<tr data-type="${esc(x.source_type)}" data-call="${esc(x.call_status||'Not called')}"><td>${x.sequence_no||''}</td><td><span class="v2-pill">${esc(x.source_type)}</span></td><td><b>${esc(x.patients?.name)}</b><div class="v2-small">${esc(x.patients?.op_no||x.patients?.ip_no||'')}</div></td><td class="v2-mobile">${esc(x.patients?.mobile||'—')}<br>${esc(x.patients?.mobile_2||'—')}</td><td>${esc(x.priority||'Routine')}</td><td class="v2-call"><select data-call-id="${x.id}">${CALL.map(c=>`<option ${c===(x.call_status||'Not called')?'selected':''}>${c}</option>`).join('')}</select></td><td><button type="button" data-edit="${x.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="7" class="v2-empty">No patients in the selected list.</td></tr>'}</tbody></table></div></div>`;
    $('wdate').onchange=()=>renderWaiting(v);$('v2-refresh').onclick=()=>renderWaiting(v);$('v2-type').onchange=filter;$('v2-call-filter').onchange=filter;
    document.querySelectorAll('[data-call-id]').forEach(e=>e.onchange=async()=>{const r=await client.from('waiting_list').update({call_status:e.value,updated_at:new Date().toISOString()}).eq('id',e.dataset.callId);if(r.error)toast(r.error.message);else e.closest('tr').dataset.call=e.value});
    document.querySelectorAll('[data-edit]').forEach(e=>e.onclick=()=>openEdit(e.dataset.edit,rows.find(x=>x.id===e.dataset.edit)));
    function filter(){const t=$('v2-type').value,c=$('v2-call-filter').value;document.querySelectorAll('#v2-wbody tr').forEach(r=>{if(!r.dataset.type){return}r.style.display=(t==='All'||r.dataset.type===t)&&(c==='All'||r.dataset.call===c)?'':'none'})}
  }
  function openEdit(id,row){const p=row?.patients||{};const m=document.createElement('div');m.className='v2-modal';m.innerHTML=`<div class="v2-modal-box"><div class="v2-title"><div><h2>Edit waiting list</h2><div class="v2-sub">${esc(p.name||'Patient')}</div></div><button type="button" class="secondary" id="v2-close">Close</button></div><div class="v2-grid"><div><label>Mobile No. 1</label><input id="e-mobile" value="${esc(p.mobile||'')}"></div><div><label>Mobile No. 2</label><input id="e-mobile2" value="${esc(p.mobile_2||'')}"></div><div><label>Priority</label><select id="e-priority">${['Routine','Priority','Urgent','Emergency'].map(x=>`<option ${x===(row?.priority||'Routine')?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Calling status</label><select id="e-call">${CALL.map(x=>`<option ${x===(row?.call_status||'Not called')?'selected':''}>${x}</option>`).join('')}</select></div><div class="v2-wide"><label>Notes</label><textarea id="e-notes">${esc(row?.notes||'')}</textarea></div></div><div class="v2-actions"><button type="button" id="v2-save-edit">Save changes</button></div></div>`;document.body.appendChild(m);$('v2-close').onclick=()=>m.remove();$('v2-save-edit').onclick=async()=>{try{const a=await client.from('patients').update({mobile:$('e-mobile').value.trim()||null,mobile_2:$('e-mobile2').value.trim()||null}).eq('id',row.patient_id);if(a.error)throw a.error;const b=await client.from('waiting_list').update({priority:$('e-priority').value,call_status:$('e-call').value,notes:$('e-notes').value,edited_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(b.error)throw b.error;m.remove();toast('Waiting list updated');renderWaiting($('view'))}catch(x){toast(x.message)}}}
  function wrapGo(){const original=window.go;if(!original)return;window.go=async function(t){if(t==='opd')return renderOPD($('view'));if(t==='major')return renderMajor($('view'));if(t==='waiting')return renderWaiting($('view'));return original(t)}}
  function reorderNav(){const nav=document.querySelector('.nav');if(!nav)return;const buttons=[...nav.querySelectorAll('button')];const find=t=>buttons.find(b=>b.textContent.trim()===t);['Dashboard','OPD Registration','Major OT','Minor OT','Endoscopy','Follow-up','OT List Generator','Waiting Lists','Sign out'].map(find).filter(Boolean).forEach(b=>nav.appendChild(b))}
  function init(){addCss();wrapGo();reorderNav();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
